name: Build and publish latest tag to Docker Hub (releases only)
on:
  release:
    types: [created]

jobs:
  build:
    name: build latest images for release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Push openvpn image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          tags: flant/ovpn-admin:openvpn-latest
          platforms: linux/amd64,linux/arm64,linux/arm,linux/386
          file:  Dockerfile.openvpn
          push: true
      - name: Push ovpn-admin image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          tags: flant/ovpn-admin:latest
          platforms: linux/amd64,linux/arm64,linux/arm,linux/386
          file: Dockerfile
          push: true