name: Build and publish to Docker Hub (tags only)
on:
  push:
    tags:
      - '*'
    
jobs:
  build:
    name: build images for tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Push openvpn image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: flant/ovpn-admin
          tags: openvpn-${{ steps.get_version.outputs.VERSION }}
          dockerfile:  Dockerfile.openvpn
      - name: Push ovpn-admin image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: flant/ovpn-admin
          tags: ${{ steps.get_version.outputs.VERSION }}
          dockerfile: Dockerfile
