name: Build and publish latest tag to Docker Hub (releases only)
on:
  release:
    types: [created]

jobs:
  build:
    name: build latest images for release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push ovpn-admin image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: erste/openvpn
          tags: latest
          dockerfile: Dockerfile
