name: Build and publish binaries (releases only)
on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 1
    strategy:
      matrix:
        goos: [linux]
        goarch: ["386", "amd64"]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: build binaries
        uses: wangyoucao577/go-release-action@v1.22
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goversion: 1.17
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          build_command: bash -ex ./build.sh
          pre_command: bash -ex ./install-deps.sh
          binary_name: "ovpn-admin"
          asset_name: ovpn-admin-${{ matrix.goos }}-${{ matrix.goarch }}
